[package]
name = "cln-grpc-routehints-test"
version = "0.1.0"
edition = "2021"


[dependencies]
tonic = { version = "0.8", features = ["tls", "transport"] }
cln-grpc = { version = "0.1.2" }
tokio = { version = "1.0", features = ["fs", "rt-multi-thread"] }
anyhow = "1.0"
hex = "0.4.3"